version: '3'

services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn leadpages_etl.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: celery -A leadpages_etl worker --loglevel=info --concurrency=4
    volumes:
      - ./app:/app
    depends_on:
      - django
      - redis

  redis:
    image: redis:alpine

  tests:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: etl_tests
    volumes:
      - ./app:/app
    depends_on:
      - django
      - redis
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=leadpages_etl.settings
    command: pytest
